[project]
name = "beet-datapack-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Reuben Daniel", email = "reubendaniel41@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "beet>=0.116.0",
    "bolt>=0.50.1",
]

[project.scripts]
beet-datapack-test = "beet_datapack_test:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
